nit_region_name   = "ap-south-1"
vpc_name          = "Nitin_Sati_VPC"
nit_ami           = "ami-05fa46471b02db0ce"
nit_instance_name = "Nitin_Sati_Instance"
nit_instance_type = "t2.micro"
nit_subnet_name   = "Nitin_Sati_Subnet"